GET http://localhost:3001/api/persons


###
GET http://localhost:3001/api/persons/64d0fc38bf50af0437904e86


###
DELETE http://localhost:3001/api/persons/64d0dca721679ab3ed8181a5


###
PUT http://localhost:3001/api/persons/64d0fc38bf50af0437904e86 HTTP/1.1
Content-Type: application/json

{
    "name": "Af",
    "number": "7076-090444"
}

###
GET http://localhost:3001/info






